matrix_shape: 
  vertical: 1
  horizontal: 11
i2c_reader:
  i2c_device_addresses: [13, 14]
  n_device_sensors: 6  # 6, 5, 4, 3
  sensor_matrix: [
    [[13, 2], [13, 1], [13, 5], [13, 3], [13, 0], [13, 4], [14, 0], [14, 1], [14, 2], [14, 3], [14, 4]],
  ]
data_preprocessor:
  calibration_period: 5000
  recalibration_period: 5000
  recalibration_window: 5000
  # calibration_period: 5
  # recalibration_period: 5
  # recalibration_window: 5
  recalibration_cluster_center_weight: 1
  n_clusters: 2
  error_threshold: 5
midi_controller:
  port: 'Virtual Raw MIDI 2-0:VirMIDI 2-0 24:0'
midi_note_player:
  n_voices: 1  
modules:
  fader:
    module: Fader
    setup:
      name: fader
      midi_channel: 2
      top: 0
      left: 0
      bottom: 1
      right: 10
    sound: 
      control_left: 13
      control_right: 14
      window_size_move: 3
      window_size_drop: 8
      error_threshold: 0 