name: 'config_real'
i2c_reader:
  i2c_device_addresses: [11, 13, 14, 15]
  n_device_sensors: 6

data_preprocessor:
  recalibration_cluster_center_weight: 8
  n_smallest_values: 20
  threshold: 0.2
  recalibration_window: 4000
  recalibration_period: 4000
  sensor_matrix: [
    [
      [ [ 13, 2 ], [ 13, 1 ], [ 13, 5 ], [ 13, 3 ], [ 13, 0 ], [ 13, 4 ], [ 14, 0 ], [ 14, 1 ], [ 14, 2 ], [ 14, 3 ], [ 14, 4 ] ]
    ],
    [ [ [ 11, 3 ], [ 11, 2 ] ], [ [ 11, 4 ], [ 11, 5 ] ] ],
    [ [ [ 15, 3 ], [ 15, 2 ] ], [ [ 15, 4 ], [ 15, 5 ] ] ]
  ]
midi_controller:
  port: 'Virtual Raw MIDI 2-0:VirMIDI 2-0 24:0'
midi_note_player:
  n_voices: 1
modules:
  fader:
    module: Fader
    setup:
      name: fader
      midi_channel: 1
      index: 0
      top: 0
      left: 0
      bottom: 1
      right: 11
    sound:
      control_left: 2
      control_right: 3
      window_size_move: 3
      window_size_drop: 8
      error_threshold: 0
  hold_1:
    module: Hold
    setup:
      name: hold_1
      midi_channel: 2
      index: 1
      top: 0
      left: 0
      bottom: 2
      right: 2
    sound:
      stack_size: 15
      time_step_size: 0.25
      delta_t_inc: 1
      delta_t_dec: 0.5
  hold_2:
    module: Hold
    setup:
      name: hold_2
      midi_channel: 3
      index: 2
      top: 0
      left: 0
      bottom: 2
      right: 2
    sound:
      stack_size: 15
      time_step_size: 0.25
      delta_t_inc: 1
      delta_t_dec: 0.5
  scene_changer:
    module: SceneChanger
    setup:
      name: scene_changer
      midi_channel: 4
      index: 0
      top: 0
      left: 0
      bottom: 0
      right: 0
    sound:
      control: 2
      scene_time: 2
      time_step_size: 20