name: 'config_real'
i2c_reader:
  i2c_device_addresses: [11, 13, 14, 15]
  n_device_sensors: 6

data_preprocessor:
  recalibration_cluster_center_weight: 8
  n_smallest_values: 20
  threshold: 0.2
  recalibration_window: 4000
  recalibration_period: 4000
  sensor_matrix: [
    [
      [ [ 13, 2 ], [ 13, 1 ], [ 13, 5 ], [ 13, 3 ], [ 13, 0 ], [ 13, 4 ], [ 14, 0 ], [ 14, 1 ], [ 14, 2 ], [ 14, 3 ], [ 14, 4 ] ]
    ],
    [ [ [ 11, 3 ], [ 11, 2 ] ], [ [ 11, 4 ], [ 11, 5 ] ] ],
    [ [ [ 15, 3 ], [ 15, 2 ] ], [ [ 15, 4 ], [ 15, 5 ] ] ]
  ]
midi_controller:
  port: 'Virtual Raw MIDI 2-0:VirMIDI 2-0 24:0'
midi_note_player:
  n_voices: 1
modules:
  scene_changer:
    module: SceneChanger
    setup:
      name: scene_changer
      midi_channel: 10
      index: 2
      top: 0
      left: 0
      bottom: 2
      right: 2
    sound:
      control: 0
      time_step_size: 5