matrix_shape: 
  vertical: 3
  horizontal: 11
i2c_reader:
  i2c_device_addresses: [11, 13, 14, 15]
  n_device_sensors: 6
  sensor_matrix: [
    [[13, 2], [13, 1], [13, 5], [13, 3], [13, 0], [13, 4], [14, 0], [14, 1], [14, 2], [14, 3], [14, 4]],
    [[11, 3], [11, 2], [15, 3], [15, 2], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0]],
    [[11, 4], [11, 5], [15, 4], [15, 5], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0]],
  ]
data_preprocessor:
  calibration_period: 50
  recalibration_period: 50
  recalibration_window: 50
  # calibration_period: 5
  # recalibration_period: 5
  # recalibration_window: 5
  recalibration_cluster_center_weight: 1
  n_clusters: 2
  error_threshold: 5
midi_controller:
  port: 'Virtual Raw MIDI 2-0:VirMIDI 2-0 24:0'
midi_note_player:
  n_voices: 1  
modules:
  fader:
    module: Fader
    setup:
      name: fader
      midi_channel: 2
      top: 0
      left: 0
      bottom: 1
      right: 10
    sound: 
      control_left: 13
      control_right: 14
      window_size_move: 3
      window_size_drop: 8
      error_threshold: 0
  wiggle:
    module: Wiggle
    setup:
      name: wiggle
      midi_channel: 2
      top: 0
      left: 0
      bottom: 2
      right: 2
    sound: 
      control: 11
      max_freq: 2
      time_step_size: 0.25
      delta_t_inc: 1
      delta_t_dec: 0.5
  hold:
    module: Hold
    setup:
      name: hold
      midi_channel: 2
      top: 0
      left: 0
      bottom: 2
      right: 2
    sound: 
      control: 15
      time_step_size: 0.25
      delta_t_inc: 3
      delta_t_dec: 1