name: 'config_real'
i2c_reader:
  i2c_device_addresses: [11, 13, 14, 15]
  n_device_sensors: 6
  sensor_matrix: [
                   [
    [[13, 2], [13, 1], [13, 5], [13, 3], [13, 0], [13, 4], [14, 0], [14, 1], [14, 2], [14, 3], [14, 4]],
    [[11, 3], [11, 2], [15, 3], [15, 2], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0]],
    [[11, 4], [11, 5], [15, 4], [15, 5], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0], [11, 0]]
                   ],
     [[[11, 3], [11, 2]], [[11, 4], [11, 5]]],
  ]
data_preprocessor:
  recalibration_cluster_center_weight: 1
  n_smallest_values: 10
  threshold: 40
  recalibration_window: 4000
  recalibration_period: 5000
midi_controller:
  port: 'Virtual Raw MIDI 2-0:VirMIDI 2-0 24:0'
midi_note_player:
  n_voices: 1
modules:
  fader_decay:
    module: Decayer
    setup:
      name: fader_decay
      midi_channel: 1
      index: 0
      top: 0
      left: 0
      bottom: 1
      right: 10
    sound:
      control: 1
      decay_rate: 0.2
      decay_delay: 8
  fader:
    module: Fader
    setup:
      name: fader
      midi_channel: 1
      index: 0
      top: 0
      left: 0
      bottom: 1
      right: 10
    sound:
      control_left: 2
      control_right: 3
      window_size_move: 3
      window_size_drop: 8
      error_threshold: 0
  # hold_decay:
  #   module: Decayer
  #   setup:
  #     name: hold_decay
  #     midi_channel: 2
  #     top: 1
  #     left: 0
  #     bottom: 3
  #     right: 2
  #   sound:
  #     control: 1
  #     decay_rate: 0.2
  #     decay_delay: 8
  # hold:
  #   module: Hold
  #   setup:
  #     name: hold
  #     midi_channel: 2
  #     top: 1
  #     left: 0
  #     bottom: 3
  #     right: 2
  #   sound:
  #     control: 2
  #     max_freq: 2
  #     time_step_size: 0.25
  #     delta_t_inc: 1
  #     delta_t_dec: 0.5
  hold_a11:
     module: Hold
     setup:
       name: hold_a11
       midi_channel: 3

       index: 1
       top: 1
       left: 2
       bottom: 2
       right: 3
     sound:
       control: 1
       time_step_size: 0.25
       delta_t_inc: 0.25
       delta_t_dec: 0.5
  hold_a12:
     module: Hold
     setup:
       name: hold_a12
       midi_channel: 4

       index: 1
       top: 2
       left: 2
       bottom: 3
       right: 3
     sound:
       control: 1
       time_step_size: 0.25
       delta_t_inc: 0.25
       delta_t_dec: 0.5
  hold_a21:
     module: Hold
     setup:
       name: hold_a21
       midi_channel: 5
       index: 1
       top: 1
       left: 3
       bottom: 2
       right: 4
     sound:
       control: 1
       time_step_size: 0.25
       delta_t_inc: 0.25
       delta_t_dec: 0.5
  hold_a22:
     module: Hold
     setup:
       name: hold_a22
       midi_channel: 6
       index: 1
       top: 2
       left: 3
       bottom: 3
       right: 4
     sound:
       control: 1
       time_step_size: 0.25
       delta_t_inc: 0.25
       delta_t_dec: 0.5


  hold_b11:
    module: Hold
    setup:
      name: hold_b11
      midi_channel: 3
      index: 1
      top: 1
      left: 0
      bottom: 2
      right: 1
    sound:
      control: 1
      time_step_size: 0.25
      delta_t_inc: 0.25
      delta_t_dec: 0.5
  hold_b12:
    module: Hold
    setup:
      name: hold_b12
      midi_channel: 4
      index: 1
      top: 2
      left: 0
      bottom: 3
      right: 1
    sound:
      control: 1
      time_step_size: 0.25
      delta_t_inc: 0.25
      delta_t_dec: 0.5
  hold_b21:
    module: Hold
    setup:
      name: hold_b21
      midi_channel: 5
      index: 1
      top: 1
      left: 1
      bottom: 2
      right: 2
    sound:
      control: 1
      time_step_size: 0.25
      delta_t_inc: 0.25
      delta_t_dec: 0.5
  hold_b22:
    module: Hold
    setup:
      name: hold_b22
      midi_channel: 6
      index: 1
      top: 2
      left: 1
      bottom: 3
      right: 2
    sound:
      control: 1
      time_step_size: 0.25
      delta_t_inc: 0.25
      delta_t_dec: 0.5
