matrix_shape: 
  vertical: 4
  horizontal: 6
i2c_reader:
  i2c_device_addresses: [15, 13, 14, 11]
  n_device_sensors: 6
  sensor_matrix: [
    [[11, 4], [11, 3], [11, 1], [15, 0], [15, 4], [15, 3]],
    [[11, 5], [11, 2], [11, 0], [15, 2], [15, 1], [15, 5]],
    [[13, 0], [13, 1], [13, 4], [14, 1], [14, 0], [14, 2]],
    [[13, 2], [13, 3], [13, 5], [14, 3], [14, 4], [14, 5]]
  ]
data_preprocessor:
  calibration_period: 500
  recalibration_period: 100
  recalibration_window: 100
  n_clusters: 2
  error_threshold: 5
midi_controller:
  port: 'Virtual Raw MIDI 2-0:VirMIDI 2-0 24:0'
  # port: 'Circuit MIDI 1'
midi_note_player:
  n_voices: 1  
modules:
  filler:
    module: Filler
    setup:
      name: filler
      midi_channel: 2
      top: 0
      left: 4
      bottom: 1
      right: 6
    sound: 
      control: 1
      fill_time: 5
      empty_time: 1
  # keyboard:
  #   module: Keyboard
  #   setup:
  #     name: keyboard1
  #     midi_channel: 0
  #     top: 0
  #     left: 0
  #     bottom: 1
  #     right: 6
  #   sound:
  #     note_mapping: [31, 33, 35, 38, 41, 43]
  #     note_duration: 1.0
  # sequencer:
  #   module: Sequencer
  #   setup:
  #     name: sequencer1
  #     midi_channel: 1
  #     top: 1
  #     left: 0
  #     bottom: 2
  #     right: 6
  #   sound:
  #     bpm: 120
  #     midi_note: 35
  #     note_duration: 0.2